---
title: "Bioconductor in R Universe"
format:
  html:
    code-fold: true
editor: visual
engine: knitr
---

Go to [windows](windows.qmd).

Using the R Universe API, this document looks at differences in packages between R Universe and Bioconductor to identify potential issues that require a fix and a processes. In particular, we compare

-   Bioconductor 3.23 and https://bioc.r-universe.dev
-   Bioconductor 3.22 and https://bioc-release.r-universe.dev

```{r install_universe, echo = FALSE, message = FALSE}
library(BiocPkgTools)
library(dplyr)
library(biocUniTools)
library(httr2)
library(reactable)
library(purrr)

.LIMIT <- 3000L
options(max.print = .LIMIT)
```

```{r get_buildurl, echo = FALSE}
# When a package fails early in the build, we don't get a _buildurl but we can
# construct it
get_buildurl <- function(pkg, uni) {
    buildurl <- tryCatch({
        u <-paste0("https://", uni, ".r-universe.dev/api/packages/", pkg)
        pkglist <- httr2::request(u) |>
            httr2::req_timeout(10) |>  # timeout after 10 seconds
            httr2::req_perform() |>
            httr2::resp_body_json()
        pkglist$`_buildurl`
        
    }, error = function(e) {
            if (is.null(e$resp)) return(NA_character_)
            body <- httr2::resp_body_string(e$resp)
            buildurl <- stringr::str_extract(body, 
                                             paste0("https://github.com/r-universe/",
                                                    uni, "/actions/runs/[0-9]+"))
            buildurl
    })
    buildurl
}
```


## R Universe and Bioconductor 3.23

```{r devel-settings, echo = FALSE, message = FALSE}
r_version <- "4.6.0"
bioc_version <- "3.23"
uni <- "bioc"
uni_os_branch <- "devel"
os <- "linux"
ru_builds <- biocUniTools::get_binaries_by_os(uni, uni_os_branch, r_version, bioc_version,
                                    os)
bbs_pkgs_i <- BiocPkgTools::biocBuildReport(version = bioc_version,
                                            pkgType = "software")
```

```{r devel-data, echo = FALSE}
bbs_builds <- bbs_pkgs_i |>
    dplyr::filter(node == "nebbiolo1", stage == "checksrc") |>
    dplyr::select(pkg, version, Deprecated, git_last_commit, result) |>
    dplyr::rename(Package = pkg, Version = version, BBS_commit = git_last_commit,
                  Check = result) |>
    dplyr::mutate(BBS_commit = substr(BBS_commit, 1, 7))
ru_builds <- biocUniTools::get_binaries_by_os(uni, uni_os_branch, r_version,
                                               bioc_version, os)

builds <- merge(bbs_builds, ru_builds, by = c("Package", "Version"),
                all.x = TRUE)

# Get _buildurl if not available
needs_url <- builds |>
    dplyr::filter(!Deprecated & is.na(`_buildurl`))
needs_url$`_buildurl` <- purrr::map_chr(needs_url$Package, get_buildurl, uni)
builds <- builds |>
    dplyr::rows_update(needs_url, by = "Package")

condensed_builds <- builds |>
    dplyr::select(Package, Version, `_buildurl`, Deprecated, BBS_commit,
                  RemoteSha, Check, `_jobs_check`, `JobUrl`,
                  `_binaries_check`, `_binaries_os`, `_binaries_arch`)

condensed_builds <- condensed_builds |>
    dplyr::rename(JobCheck = `_jobs_check`, BinariesCheck = `_binaries_check`,
                  BuildUrl = `_buildurl`, RU_commit = RemoteSha) |>
    dplyr::mutate(RU_commit = substr(RU_commit, 1, 7)) |>
    dplyr::mutate(CommitMatch = BBS_commit == RU_commit) |>
    dplyr::select(Package, Version, BBS_commit, Deprecated, CommitMatch,
                  Check, JobCheck, BinariesCheck, JobUrl, BuildUrl)

condensed_builds_display <- condensed_builds |>
    dplyr::mutate(
        JobCheck = ifelse(!is.na(JobUrl),
            paste0('<a href="', JobUrl, '" target="_blank">', JobCheck, '</a>'),
            as.character(JobCheck)),
        BinariesCheck = ifelse(!is.na(BuildUrl),
            paste0('<a href="', BuildUrl, '" target="_blank">', BinariesCheck, '</a>'),
            as.character(BinariesCheck))
    ) |>
    dplyr::select(-JobUrl, -BuildUrl)

reactable::reactable(condensed_builds_display, searchable = TRUE,
                     showPageSizeOptions = TRUE, compact = TRUE,
                     columns = list(
                         JobCheck = reactable::colDef(html = TRUE),
                         BinariesCheck = reactable::colDef(html = TRUE)
                     )
)
```

## R Universe and Bioconductor 3.22

```{r release-settings, echo = FALSE, message = FALSE}
r_version <- "4.5.0"
bioc_version <- "3.22"
uni_os_branch <- "release"
uni <- "bioc-release"
ru_builds <- biocUniTools::get_binaries_by_os(uni, uni_os_branch, r_version, bioc_version,
                                    os)
bbs_pkgs_i <- BiocPkgTools::biocBuildReport(version = bioc_version,
                                            pkgType = "software")
```

```{r release-data, echo = FALSE}
bbs_builds <- bbs_pkgs_i |>
    dplyr::filter(node == "nebbiolo2", stage == "checksrc") |>
    dplyr::select(pkg, version, Deprecated, git_last_commit, result) |>
    dplyr::rename(Package = pkg, Version = version, BBS_commit = git_last_commit,
                  Check = result)
ru_builds <- biocUniTools::get_binaries_by_os(uni, uni_os_branch, r_version,
                                              bioc_version, os)

builds <- merge(bbs_builds, ru_builds, by = c("Package", "Version"),
                all.x = TRUE)

# Get _buildurl if not available
needs_url <- builds |>
    dplyr::filter(!Deprecated & is.na(`_buildurl`))
needs_url$`_buildurl` <- purrr::map_chr(needs_url$Package, get_buildurl, uni)
builds <- builds |>
    dplyr::rows_update(needs_url, by = "Package")

condensed_builds <- builds |>
    dplyr::select(Package, Version, `_buildurl`, Deprecated, BBS_commit,
                  RemoteSha, Check, `_jobs_check`, `JobUrl`,
                  `_binaries_check`, `_binaries_os`, `_binaries_arch`)

condensed_builds <- condensed_builds |>
    dplyr::rename(JobCheck = `_jobs_check`, BinariesCheck = `_binaries_check`,
                  BuildUrl = `_buildurl`, RU_commit = RemoteSha) |>
    dplyr::mutate(RU_commit = substr(RU_commit, 1, 7)) |>
    dplyr::mutate(CommitMatch = BBS_commit == RU_commit) |>
    dplyr::select(Package, Version, BBS_commit, Deprecated, CommitMatch,
                  Check, JobCheck, BinariesCheck, JobUrl, BuildUrl)

condensed_builds_display <- condensed_builds |>
    dplyr::mutate(
        JobCheck = ifelse(!is.na(JobUrl),
            paste0('<a href="', JobUrl, '" target="_blank">', JobCheck, '</a>'),
            as.character(JobCheck)),
        BinariesCheck = ifelse(!is.na(BuildUrl),
            paste0('<a href="', BuildUrl, '" target="_blank">', BinariesCheck, '</a>'),
            as.character(BinariesCheck))
    ) |>
    dplyr::select(-JobUrl, -BuildUrl)

reactable::reactable(condensed_builds_display, searchable = TRUE,
                     showPageSizeOptions = TRUE, compact = TRUE,
                     columns = list(
                         JobCheck = reactable::colDef(html = TRUE),
                         BinariesCheck = reactable::colDef(html = TRUE)
                     )
)
```

```{r sessionInfo}
sessionInfo()
```
