on:
  push:
    branches: [devel]
  pull_request:
    branches: [devel]
  schedule:
    - cron: "30 16 * * *" # 2:30pm ET 
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: quarto-dev/quarto-actions/setup@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::pkgdown
            any::remotes
          needs: website

      - name: Install package
        run: BiocManager::install("Bioconductor/biocUniTools")
        shell: Rscript {0}

      - name: Render Quarto document
        run: quarto render path/to/yourfile.qmd --output-dir docs/articles

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean: false
          branch: gh-pages
          folder: docs
